version: "3"
services:
  ddns-dnspod:
    image: stilleshan/ddns-dnspod
    container_name: ddns-dnspod
    environment:
      - login_token=token_id,token
      - domain=domain.com
      - sub_domain=www
      - interval=10
      - ip_count=1
    restart: always

